
export const IMAGE = require('../assets/images/image.jpg')
export const IMAGE2X = require('../assets/images/image@2x.jpg')
export const IMAGE3X = require('../assets/images/image@3x.jpg')

export const ARROW_DOWN_SM = require('../assets/svg/arrow-down-small.svg')
export const ARROW_LEFT_LG = require('../assets/svg/arrow-left-large.svg')
export const ARROW_LEFT_SM = require('../assets/svg/arrow-left-small.svg')
export const ARROW_LEFT_WHITE = require('../assets/svg/arrow-left-white.svg')
export const ARROW_RIGHT_LG = require('../assets/svg/arrow-right-large.svg')
export const ARROW_RIGHT_SM = require('../assets/svg/arrow-right-small.svg')
export const CLOCK = require('../assets/svg/clock.svg')
export const FILTER = require('../assets/svg/filter.svg')
export const GLOBE = require('../assets/svg/globe.svg')
export const HEART = require('../assets/svg/heart.svg')
export const PHONE = require('../assets/svg/phone.svg')
export const PIN = require('../assets/svg/pin.svg')
export const STAR = require('../assets/svg/star.svg')
export const STAR_FILL = require('../assets/svg/star-fill.svg')
